version: "3.1"

services:

  command:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: command
    ports:
      - 3000:3000

  viking:
    image: jstone28/mars-viking:latest
    container_name: viking
    ports:
      - 4000:4000
